@Restaurants.API_HostAddress = https://localhost:7108



GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/28

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
"Name" : "la la",
"Description" : "Best coffee from all tong",
"Category" : "French",
"HasDelivery" : true,
"ContactEmail" : "chgmail@gmai.com",
"ContactNumber" : "01444223366",
"City" : "Dhaka",
"Street" : "Gulshan 1",
"PostalCode" : "123456"

}

###

@id=18
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "Name" : "Okay cha",
  "Description" : "No okay cha"
}

###
